export enum Units {
    Enum = 'enum',
    String = 'string',
    Boolean = 'bool',
    Feet = 'feet',
    FeetPerMinute = 'feet per minute',
    FeetPerSecond = 'feet per second',
    InchesOfMercury = 'inches of mercury',
    Millibars = 'millibars',
    Percent = 'percent',
    Celsius = 'celsius',
    PoundsPerHour = 'pounds per hour',
    Number = 'number',
    Psi = 'psi',
    Degrees = 'degrees',
    Pounds = 'pounds',
    Gallons = 'gallons',
    PercentOver100 = 'percent over 100',
    Position = 'position',
    Position16K = 'position `16K',
    Position32K = 'position `32K',
    Position128 = 'position `128',
    MetresPerSecond = 'metres per second',
    GForce = 'g force',
    Knots = 'knots',
    FeetPerSecondSquared = 'feet per second squared',
    Second = 'seconds',
}
